CREATE TABLE PRODUCTOS(
	PRODUCTOID VARCHAR2(3) CONSTRAINT PK_PRODUCTOS_PRODUCTOID PRIMARY KEY,
	NOMBRE VARCHAR2(40) NOT NULL,
	PRECIO NUMBER(4,2) NOT NULL,
	DESCRIPCION VARCHAR2(100)
);

CREATE TABLE EMPLEADOS(
	EMPLEADOID VARCHAR2(4) CONSTRAINT PK_EMPLEADOS_EMPLEADOID PRIMARY KEY,
	NOMBRE VARCHAR2(40) NOT NULL,
	FECHA_CONTRATO DATE,
	TELEFONO VARCHAR2(11)
);


CREATE TABLE CLIENTES(
	CLIENTEID VARCHAR2(4) CONSTRAINT PK_CLIENTES_CLIENTEID PRIMARY KEY,
	NOMBRE VARCHAR(40), NOT NULL,
	APELLIDO VARCHAR(40), NOT NULL;
	TELEFONO VARCHAR2(11)	
);


CREATE TABLE PEDIDOS(
	PEDIDOID VARCHAR2(4) CONSTRAINT PK_PEDIDOS_PEDIDOID PRIMARY KEY,
	NUMERO_MESA INT NOT NULL,
	TOTAL NUMBER(4,2) NOT NULL,
	FECHA_PEDIDO DATE,
	CLIENTEID(4) CONSTRAINT FK_PEDIDOS_CLIENTEID REFERENCES CLIENTES(CLIENTEID),
	EMPLEADOID(4) CONSTRAINT FK_PEDIDOS_EMPLEADOID REFERENCES EMPLEADOS(EMPLEADOID)
);

CREATE TABLE DETALLES_PEDIDO(
	DETALLE_PEDIDO_ID VARCHAR2(4) CONSTRAINT PK_DETALLE_PEDIDO_PEDIDOID PRIMARY KEY,
	PRECIO_UNIDAD NUMBER(5,2) NOT NULL,
	CANTIDAD INT,
	TOTAL NUMBER(4,2) NOT NULL,
	PEDIDOID(4) CONSTRAINT FK_DETALLES_PEDIDO_PEDIDOID REFERENCES PEDIDO(PEDIDOID),
	PRODUCTOID(4)CONSTRAINT FK_DETALLES_PEDIDO_PRODUCTOID REFERENCES PRODUCTO(PRODUCTOID)
);

